project_name: ds_flow

paths:
  input_pattern: "data/student_*.csv"
  data_dir: "data"
  output_dir: "out"
  log_dir: "log"

compute:
  lsf_queue: "short"
  docker_image: "ubuntu"
  sample_batches:
    - "Batch1"
    - "Batch2"
